### Week 9 
Natural Language Processing 
* Vocab
https://www.kdnuggets.com/2017/02/natural-language-processing-key-terms-explained.html

* Link to TM guide
https://cran.r-project.org/web/packages/tm/vignettes/tm.pdf

## Generate data
```{R}

corpus = c('I want a cup of coffee', 
         'please get me a coffee',
         'please give me a cup of coffee' ,
         'I hate coffee', 
         'no thanks, I don not want a coffee right now',
          'no coffee for me',
         'I already had 1, thank you',
         'more coffee please',
         'can I have a frapacino',
         'can I get bagel',
         'green tea latte please')
labels = c(1,1,1,0,0,0,0,1,1,0,0 )
length(labels)
length(corpus)
```

### lower case everything
```{r}
library(tm)
print(corpus)
docs <- Corpus(VectorSource(corpus))
docs <- tm_map(docs, content_transformer(tolower))
inspect(docs)
```


### Remove Numbers
```{r}
inspect(docs)
docs <- tm_map(docs, removeNumbers)
inspect(docs)
```

#### Remove Stop Words
```{r}
#stopwords("english")
docs <- tm_map(docs, removeWords, c('the', 'i'))

inspect(docs)
```


#### Eliminate extra white spaces
```{r}
docs <- tm_map(docs, stripWhitespace)

inspect(docs)
```

```{r}
# Text stemming (reduces words to their root form)
#library("SnowballC")
#docs <- tm_map(docs, stemDocument)
#inspect(docs)
```

```{r}

dtm <- TermDocumentMatrix(docs)
m <- t(as.matrix(dtm))
print(m)
```


```{r}

x = data.frame(m)
x$labels = labels
fit <- glm(labels~., family = 'binomial', data=x)
exp(coef(fit))
```

### Example of a fully form text preprocess function

```{r}
text_proc <- function(text){
  library(tm)
  library("SnowballC")
  docs <- Corpus(VectorSource(c(corpus, text)))
  docs <- tm_map(docs, tolower)
  docs <- tm_map(docs, removeWords, c( 'the', 'i'))
  docs <- tm_map(docs, removeNumbers)
  dtm <- TermDocumentMatrix(docs)
  m <- data.frame(t(as.matrix(dtm)))
  return(tail(m,1))
}
text_proc('this is my new coffee order unseen to the data set')
```


### test the prediction
```{r}
z = text_proc('hate it at starbucks')

predict(fit, z, type='response')
predict(fit, z, type='response')
```


